Conform to Standards Version 3.9.8.
By converting the build process to use debhelper and include rules to
create the documentation and language support files, we can guarantee
that the builds are completely reproducible.

Closes: #777730
Closes: #793004

diff --git a/debdelta/debian/postrm b/debdelta/debian/postrm
--- a/debdelta/debian/postrm
+++ b/debdelta/debian/postrm
@@ -1,5 +1,23 @@
 #!/bin/sh
+# postrm script for debdelta
+#
+# see: dh_installdeb(1)
+
 set -e
+
+# summary of how this script can be called:
+#        * <postrm> `remove'
+#        * <postrm> `purge'
+#        * <old-postrm> `upgrade' <new-version>
+#        * <new-postrm> `failed-upgrade' <old-version>
+#        * <new-postrm> `abort-install'
+#        * <new-postrm> `abort-install' <old-version>
+#        * <new-postrm> `abort-upgrade' <old-version>
+#        * <disappearer's-postrm> `disappear' <overwriter>
+#          <overwriter-version>
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
+
 
 GPG_HOME=/etc/debdelta/gnupg
 
@@ -10,21 +28,37 @@ check1it () {
  )
 }
 
-if [ "$1" = purge ] ; then
-  if  [ -r /var/lib/debdelta ] ; then
-    rm -r /var/lib/debdelta
-  fi
+case "$1" in
+  purge)
+    if  [ -r /var/lib/debdelta ] ; then
+      rm -r /var/lib/debdelta
+    fi
 
-  if check1it ; then
-    (
-      cd ${GPG_HOME}
-      rm -f pubring.gpg  secring.gpg  trustdb.gpg
-      if test -f pubring.gpg~ ; then
-          rm -f pubring.gpg~
-      fi
-      rm -f sha1_hashes.txt
-    )
-    rmdir ${GPG_HOME} || true
-  fi
+    if check1it ; then
+      (
+        cd ${GPG_HOME}
+        rm -f pubring.gpg  secring.gpg  trustdb.gpg
+        if test -f pubring.gpg~ ; then
+            rm -f pubring.gpg~
+        fi
+        rm -f sha1_hashes.txt
+      )
+      rmdir ${GPG_HOME} || true
+    fi
+    ;;
 
-fi
+  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+    ;;
+
+  *)
+    echo "postrm called with unknown argument \`$1'" >&2
+    exit 1
+    ;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
